---
title: "Example Report"
output: html_document
params:
   reactValues: NULL
   checkDesign: NULL
   checkDesignOptionsTables: NULL 
   checkDesignOptionsPlots: NULL
   checkNoLook: NULL
   checkNoLookOptionsTables: NULL 
   checkNoLookOptionsPlots: NULL
   noLookFuncPlot: NULL
   noLookFuncSS: NULL
   checkOneLook: NULL
   checkOneLookOptionsTables: NULL 
   checkOneLookOptionsPlots: NULL
   spendingOneLook: NULL 
   oneLookBoundaryIA: NULL 
   oneLookFunc: NULL 
   checkTwoLooks: NULL
   checkTwoLooksOptionsTables: NULL 
   checkTwoLooksOptionsPlots: NULL 
   spendingTwoLooks: NULL 
   twoLooksBoundaryIA: NULL 
   twoLooksFunc: NULL 
   checkBayesian: NULL 
   checkBayesianOptionsTables: NULL 
   checkBayesianOptionsPlots: NULL
   BPPVec: NULL
   
                     
---

```{r setup, echo = F}

rowCallback <- c(
  "function(row, data){",
  "  for(var i=0; i<data.length; i++){",
  "    if(data[i] === null){",
  "      $('td:eq('+i+')', row).html('NA')",
  "        .css({'color': 'rgb(151,151,151)', 'font-style': 'italic'});",
  "    }",
  "  }",
  "}"
)

library(knitr)
library(DT)
library(plotly)
library(htmlwidgets)

```


### Design

```{r design, echo = F}

if (params$checkDesign){
  
  if (!is.null(params$checkDesignOptionsPlots)){
     
    if ("Elicited T" %in% params$checkDesignOptionsPlots){
        SHELF::plotfit(params$reactValues$treatmentSamplesDF$fit1, d = params$reactValues$treatmentSamplesDF$d[1])
    }
    
    if ("Elicited post-delay HR" %in% params$checkDesignOptionsPlots){
        SHELF::plotfit(params$reactValues$treatmentSamplesDF$fit2, d = params$reactValues$treatmentSamplesDF$d[2])
    }
    
  }
  
}


```

### No Look


```{r noLook, echo = F}

if (params$checkNoLook){
  
  if (!is.null(params$checkNoLookOptionsTables)){
    
    if ("Assurance OC" %in% params$checkNoLookOptionsTables){
       plot(params$noLookFuncPlot$myDF$SampleSize*2, predict(params$noLookFuncPlot$smoothedPower), ylim = c(0,1), type = "l", xlab = "Number of Events", ylab = "Assurance")
    }
    
  }
  
  if (!is.null(params$checkNoLookOptionsPlots)){
    
    if ("Assurance Plot" %in% params$checkNoLookOptionsPlots){
         params$noLookFuncSS
    }
    
  }
  
}

```


### One Look

```{r oneLook, echo = F}
# Initialize plot variables
boundary_plot <- NULL
assurance_vs_duration_plot <- NULL
assurance_vs_sample_size_plot <- NULL
datatable_output <- NULL

if (params$checkOneLook){
  
  if (!is.null(params$checkOneLookOptionsTables)){
    
    # Operating Characteristics Table
    IADFOneLook <- subset(params$oneLookFunc$IADFOneLook, select = c("Information Fraction", params$checkOneLookOptionsTables))
    
    datatable_output <- datatable(IADFOneLook, options = list(rowCallback = JS(rowCallback)),
                                  rownames = F) %>% formatStyle(
                                    columns = colnames(IADFOneLook)
                                  ) %>%
      formatSignif(
        columns = colnames(IADFOneLook),
        digits = 3
      )
  }
  
  if (!is.null(params$checkOneLookOptionsPlots)){

    if ("Boundary Plot" %in% params$checkOneLookOptionsPlots){

      # Boundary Plot
      values <- hot_to_r(params$spendingOneLook)
      design <- getDesignGroupSequential(typeOfDesign = "asUser", 
                                         informationRates = c(as.numeric(params$oneLookBoundaryIA), 1),
                                         userAlphaSpending = as.numeric(values[,2]), 
                                         typeBetaSpending = "bsUser",
                                         userBetaSpending = as.numeric(values[,3]))
      boundary_plot <- plot(design)
    }
    
    if ("Assurance vs Duration" %in% params$checkOneLookOptionsPlots){

      # Assurance vs Duration Plot
      assurance_vs_duration_plot <- plot_ly(params$oneLookFunc$IADFOneLook, x = ~Assurance, y = ~Duration,
                                            text = ~ paste0("Information Fraction = ", `Information Fraction`), mode = "markers",
                                            type = "scatter", marker = list(size = 10, color = "blue"), name = "Chosen Rules") %>%
        add_trace(x = ~params$oneLookFunc$FinalAss$Assurance, y = ~params$oneLookFunc$FinalAss$Duration, type = "scatter", mode = "markers", 
                  marker = list(size = 10, color = "red"), 
                  text = ~ "No Interim Analysis",
                  name = "No Interim Analysis") %>%
        layout(
          xaxis = list(title = list(text = "Assurance", font = list(color = "black", size = 14, family = "Arial", weight = "bold")), range = c(0, 1)),
          yaxis = list(title = list(text = "Duration", font = list(color = "black", size = 14, family = "Arial", weight = "bold"))),
          legend = list(orientation = "v", x = 1.05, y = 0.5),  # Position legend to the right
          title = "Assurance vs Duration for the different stopping rules"
        )
    }
    
    if ("Assurance vs Sample Size" %in% params$checkOneLookOptionsPlots){

      # Assurance vs Sample Size Plot
      assurance_vs_sample_size_plot <- plot_ly(params$oneLookFunc$IADFOneLook, x = ~Assurance, y = ~`Sample Size`,
                                               text = ~ paste0("Information Fraction = ", `Information Fraction`), mode = "markers",
                                               type = "scatter", marker = list(size = 10, color = "blue"), name = "Chosen Rules") %>%
        add_trace(x = ~params$oneLookFunc$FinalAss$Assurance, y = ~params$oneLookFunc$FinalAss$`Sample Size`, type = "scatter", mode = "markers", 
                  marker = list(size = 10, color = "red"), 
                  text = ~ "No Interim Analysis",
                  name = "No Interim Analysis") %>%
        layout(
          xaxis = list(title = list(text = "Assurance", font = list(color = "black", size = 14, family = "Arial", weight = "bold")), range = c(0, 1)),
          yaxis = list(title = list(text = "Sample Size", font = list(color = "black", size = 14, family = "Arial", weight = "bold"))),
          legend = list(orientation = "v", x = 1.05, y = 0.5),  # Position legend to the right
          title = "Assurance vs Sample Size for the different stopping rules"
        )
    }
  }
}

# Print the datatable and plots outside the conditional blocks
if (!is.null(datatable_output)) {
  htmltools::tagList(list(datatable_output))
}
if (!is.null(boundary_plot)) {
  print(boundary_plot)
}
if (!is.null(assurance_vs_duration_plot)) {
  htmltools::tagList(list(assurance_vs_duration_plot))
}
if (!is.null(assurance_vs_sample_size_plot)) {
  htmltools::tagList(list(assurance_vs_sample_size_plot))
}
```

### Two Looks

```{r twoLooks, echo = F}

boundary_plot <- NULL
assurance_vs_duration_plot <- NULL
assurance_vs_sample_size_plot <- NULL
datatable_output <- NULL

if (params$checkTwoLooks){
  
    if (!is.null(params$checkTwoLooksOptionsTables)){
      
      
       IADFTwoLooks <- subset(params$twoLooksFunc$IADFTwoLooks, select = c("Information Fraction", params$checkTwoLooksOptionsTables))
      
      datatable_output <- datatable(IADFTwoLooks, options = list(rowCallback = JS(rowCallback)),
                rownames = F) %>% formatStyle(
                  columns = colnames(IADFTwoLooks)
                ) %>%
        formatSignif(
          columns = colnames(IADFTwoLooks),
          digits = 3
        )

    }
  
  if (!is.null(params$checkTwoLooksOptionsPlots)){
    
        if ("Boundary Plot" %in% params$checkTwoLooksOptionsPlots){

    
    #Boundary Plot
  values <- hot_to_r(params$spendingTwoLooks)
    
    
      design <- getDesignGroupSequential(typeOfDesign = "asUser", 
                                         informationRates = as.numeric(c(strsplit(params$twoLooksBoundaryIA, ", ")[[1]], 1)), 
                                         userAlphaSpending = as.numeric(values[,2]), 
                                         typeBetaSpending = "bsUser",
                                         userBetaSpending = as.numeric(values[,3]))
      
      
        boundary_plot <- plot(design)
    
    
        }
    
    if ("Assurance vs Duration" %in% params$checkTwoLooksOptionsPlots){

  
   assurance_vs_duration_plot <- plot_ly(params$twoLooksFunc$IADFTwoLooks, x = ~Assurance, y = ~Duration,
                   text = ~ paste0("Information Fraction = ", `Information Fraction 1`, ", ", `Information Fraction 2`), mode = "markers",
                   type = "scatter", marker = list(size = 10, color = "blue"), name = "Chosen Rules") %>%
        add_trace(x = ~params$twoLooksFunc$FinalAss$Assurance, y = ~params$twoLooksFunc$FinalAss$Duration, type = "scatter", mode = "markers",
                  marker = list(size = 10, color = "red"),
                  text = ~ "No Interim Analysis",
                  name = "No Interim Analysis") %>%
        add_trace(x = ~params$twoLooksFunc$FinalProposedDF$Assurance, y = ~params$twoLooksFunc$FinalProposedDF$Duration, type = "scatter", mode = "markers",
                  marker = list(size = 10, color = "green"),
                  text = ~ "Proposed Rule",
                  name = "Proposed Rule") %>%
        layout(
          xaxis = list(title = list(text = "Assurance", font = list(color = "black", size = 14, family = "Arial", weight = "bold")), range = c(0, 1)),
          yaxis = list(title = list(text = "Duration", font = list(color = "black", size = 14, family = "Arial", weight = "bold"))),
          legend = list(orientation = "v", x = 1.05, y = 0.5),  # Position legend to the right
          title = "Assurance vs Duration for the different stopping rules"
        )
      
    }
    
    if ("Assurance vs Sample Size" %in% params$checkTwoLooksOptionsPlots){
      
       assurance_vs_sample_size_plot <- plot_ly(params$twoLooksFunc$IADFTwoLooks, x = ~Assurance, y = ~`Sample Size`,
                   text = ~ paste0("Information Fraction = ", `Information Fraction 1`, ", ", `Information Fraction 2`), mode = "markers",
                   type = "scatter", marker = list(size = 10, color = "blue"), name = "Chosen Rules") %>%
        add_trace(x = ~params$twoLooksFunc$FinalAss$Assurance, y = ~params$twoLooksFunc$FinalAss$`Sample Size`, type = "scatter", mode = "markers",
                  marker = list(size = 10, color = "red"),
                  text = ~ "No Interim Analysis",
                  name = "No Interim Analysis") %>%
        add_trace(x = ~params$twoLooksFunc$FinalProposedDF$Assurance, y = ~params$twoLooksFunc$FinalProposedDF$`Sample Size`, type = "scatter", mode = "markers",
                  marker = list(size = 10, color = "green"),
                  text = ~ "Proposed Rule",
                  name = "Proposed Rule") %>%
        layout(
          xaxis = list(title = list(text = "Assurance", font = list(color = "black", size = 14, family = "Arial", weight = "bold")), range = c(0, 1)),
          yaxis = list(title = list(text = "Sample Size", font = list(color = "black", size = 14, family = "Arial", weight = "bold"))),
          legend = list(orientation = "v", x = 1.05, y = 0.5),  # Position legend to the right
          title = "Assurance vs Sample Size for the different stopping rules"
        )
      
}
  
  
      
  }
}
if (!is.null(datatable_output)) {
  htmltools::tagList(list(datatable_output))
}
if (!is.null(boundary_plot)) {
  print(boundary_plot)
}
if (!is.null(assurance_vs_duration_plot)) {
  htmltools::tagList(list(assurance_vs_duration_plot))
}
if (!is.null(assurance_vs_sample_size_plot)) {
  htmltools::tagList(list(assurance_vs_sample_size_plot))
}


```

### Bayesian


```{r bayesian, echo = F}


BPP_Plot <- NULL
TE_Plot <- NULL
BPP_TE_Plot <- NULL


if (params$checkBayesian){



  if (!is.null(params$checkBayesianOptionsTables)){

  }

  if (!is.null(params$checkBayesianOptionsPlots)){

    if ("BPP Plot" %in% params$checkBayesianOptionsPlots){

     # Plotting histogram colored by ColorVar
    BPP_Plot <- ggplot(params$BPPVec$BPPVec, aes(x = BPP, fill = Success)) +
        geom_histogram(position = "identity", alpha = 0.5) +
        scale_x_continuous(limits = c(0, 1)) + xlab("Bayesian Predictive Probability")

    }

    if ("Target Effectiveness Plot" %in% params$checkBayesianOptionsPlots){

       # Plotting histogram colored by ColorVar
     TE_Plot <- ggplot(params$BPPVec$BPPVec, aes(x = propEffect, fill = Success)) +
        geom_histogram(position = "identity", alpha = 0.5) +
        scale_x_continuous(limits = c(0, 1)) + xlab("Proportion less than target effect")

    }

    if ("BPP vs TE Plot" %in% params$checkBayesianOptionsPlots){

    BPP_TE_Plot <- ggplot(params$BPPVec$BPPVec, aes(x = BPP, y = propEffect)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  xlab("Bayesian Predictive Probability") +
  ylab("Proportion less than target effect")

    }


  }


}


if (!is.null(BPP_Plot)) {
      print(BPP_Plot)
}
if (!is.null(TE_Plot)) {
  TE_Plot
}
if (!is.null(BPP_TE_Plot)) {
  BPP_TE_Plot
}

```




